### PR TITLE
external points event

### PR DESCRIPTION
**Pull request by LlemonDuck**
- **project: add lombok to test classpath**
- **util: external plugin event framework**
- **pointstracker: post points to eventbus at raid end**

### CODE REVIEW

**Comment by LlemonDuck** [comment]
@null-zero Can you try this build and see if it posts what you need to the bus?

You'll need to copy `ExternalPluginEvent.java` and `ToAPointsEvent.java` into somewhere in your project, and use them as shown in the `ExternalPluginEvent` javadoc: https://github.com/LlemonDuck/tombs-of-amascut/blob/684b457f9bdd35637fd4c9cdd41459536dd67ede/src/main/java/com/duckblade/osrs/toa/util/ExternalPluginEvent.java#L62-L77

If it looks good to you, I'll release it :)

**Comment by LlemonDuck** [comment]
A quick update, this PR prompted some discussion going on for core to include some sort of inter-plugin messaging. This may end up held back until that's resolved.

Conversation starts here: https://discord.com/channels/301497432909414422/419891709883973642/1263992474310021221

**Comment by LlemonDuck** [comment]
Ok, that's much simpler, and a more elegant interface to boot. This will have to wait to be published until the next RuneLite release, which is probably next Wednesday if nothing happens sooner.

**Comment by null-zero** [comment]
I don't mind waiting one bit, especially when other plugins will benefit from this change, too. I know Gudi asked about inter-plugin communication not long ago, so I know plenty of people will be thankful for the core update. 

My one ask is that the event post happens after warden but before players leave the tomb, as that's when the raid is "finished" as far as points go, though that's a little nitpicky, and something I can work around if you prefer it after players leave the tomb.

Thanks again for all of your help as well as Adam's and jocopa3 for their pr 😊

**Comment by LlemonDuck** [comment]
The reason I have it upon leaving the tomb is to give time for the other party members' point totals to be received.

I can replace the room leave trigger with a tick timer after Wardens die, and that should work all the same.

**Comment by LlemonDuck** [comment]
@null-zero this is now being released to the plugin hub. Feel free to ping me here or in the RL server if you run into any problems consuming it :)

**Comment by null-zero** [comment]
Lovely!! Thank you!

**Pull request merged**
